### ISSUE TITLE
Invisible Text

### ISSUE THREAD

**Issue by Richie-exe** [cgsdiscord/deeds-cord#22] opened 2021-10-20 23:07 UTC
Mesa cannot see da text.

Occurrences:
-New page (selecting thing on the right)
-The "Are you sure you want to submit" thing after completing a quiz
-When reviewing the results of a quiz
-On the "start" page of a quiz

![image](https://user-images.githubusercontent.com/92895541/138184519-b605e786-d94e-493a-bbbc-ff8862376364.png)
![image](https://user-images.githubusercontent.com/92895541/138184455-abc7f2bc-e4c9-426f-aedb-8a537d990890.png)
![image](https://user-images.githubusercontent.com/92895541/138184563-3634b658-7c55-4a62-b990-93c598e35220.png)

(couldn't replicate the complete quiz thing)

**Comment by Dumbledore-web** [comment] 2021-10-20 23:08
Duplicate of #18

**Closed** 2021-11-09 06:32 UTC
Labels: duplicate
